export interface SurahInfo {
    number: number;
    name: string;
    totalAyat: number;
}

/** 114 surat Al-Qur'an dengan jumlah ayat, dipakai untuk dropdown pilihan surat dan validasi
 *  batas ayat (mis. mencegah input "Al-Ikhlas ayat 10" padahal surat itu cuma 4 ayat). */
export const SURAH_LIST: SurahInfo[] = [
    { number: 1, name: "Al-Fatihah", totalAyat: 7 },
    { number: 2, name: "Al-Baqarah", totalAyat: 286 },
    { number: 3, name: "Ali 'Imran", totalAyat: 200 },
    { number: 4, name: "An-Nisa", totalAyat: 176 },
    { number: 5, name: "Al-Ma'idah", totalAyat: 120 },
    { number: 6, name: "Al-An'am", totalAyat: 165 },
    { number: 7, name: "Al-A'raf", totalAyat: 206 },
    { number: 8, name: "Al-Anfal", totalAyat: 75 },
    { number: 9, name: "At-Taubah", totalAyat: 129 },
    { number: 10, name: "Yunus", totalAyat: 109 },
    { number: 11, name: "Hud", totalAyat: 123 },
    { number: 12, name: "Yusuf", totalAyat: 111 },
    { number: 13, name: "Ar-Ra'd", totalAyat: 43 },
    { number: 14, name: "Ibrahim", totalAyat: 52 },
    { number: 15, name: "Al-Hijr", totalAyat: 99 },
    { number: 16, name: "An-Nahl", totalAyat: 128 },
    { number: 17, name: "Al-Isra", totalAyat: 111 },
    { number: 18, name: "Al-Kahfi", totalAyat: 110 },
    { number: 19, name: "Maryam", totalAyat: 98 },
    { number: 20, name: "Thaha", totalAyat: 135 },
    { number: 21, name: "Al-Anbiya", totalAyat: 112 },
    { number: 22, name: "Al-Hajj", totalAyat: 78 },
    { number: 23, name: "Al-Mu'minun", totalAyat: 118 },
    { number: 24, name: "An-Nur", totalAyat: 64 },
    { number: 25, name: "Al-Furqan", totalAyat: 77 },
    { number: 26, name: "Asy-Syu'ara", totalAyat: 227 },
    { number: 27, name: "An-Naml", totalAyat: 93 },
    { number: 28, name: "Al-Qashash", totalAyat: 88 },
    { number: 29, name: "Al-'Ankabut", totalAyat: 69 },
    { number: 30, name: "Ar-Rum", totalAyat: 60 },
    { number: 31, name: "Luqman", totalAyat: 34 },
    { number: 32, name: "As-Sajdah", totalAyat: 30 },
    { number: 33, name: "Al-Ahzab", totalAyat: 73 },
    { number: 34, name: "Saba'", totalAyat: 54 },
    { number: 35, name: "Fathir", totalAyat: 45 },
    { number: 36, name: "Yasin", totalAyat: 83 },
    { number: 37, name: "Ash-Shaffat", totalAyat: 182 },
    { number: 38, name: "Shad", totalAyat: 88 },
    { number: 39, name: "Az-Zumar", totalAyat: 75 },
    { number: 40, name: "Ghafir", totalAyat: 85 },
    { number: 41, name: "Fushshilat", totalAyat: 54 },
    { number: 42, name: "Asy-Syura", totalAyat: 53 },
    { number: 43, name: "Az-Zukhruf", totalAyat: 89 },
    { number: 44, name: "Ad-Dukhan", totalAyat: 59 },
    { number: 45, name: "Al-Jatsiyah", totalAyat: 37 },
    { number: 46, name: "Al-Ahqaf", totalAyat: 35 },
    { number: 47, name: "Muhammad", totalAyat: 38 },
    { number: 48, name: "Al-Fath", totalAyat: 29 },
    { number: 49, name: "Al-Hujurat", totalAyat: 18 },
    { number: 50, name: "Qaf", totalAyat: 45 },
    { number: 51, name: "Adz-Dzariyat", totalAyat: 60 },
    { number: 52, name: "Ath-Thur", totalAyat: 49 },
    { number: 53, name: "An-Najm", totalAyat: 62 },
    { number: 54, name: "Al-Qamar", totalAyat: 55 },
    { number: 55, name: "Ar-Rahman", totalAyat: 78 },
    { number: 56, name: "Al-Waqi'ah", totalAyat: 96 },
    { number: 57, name: "Al-Hadid", totalAyat: 29 },
    { number: 58, name: "Al-Mujadilah", totalAyat: 22 },
    { number: 59, name: "Al-Hasyr", totalAyat: 24 },
    { number: 60, name: "Al-Mumtahanah", totalAyat: 13 },
    { number: 61, name: "Ash-Shaff", totalAyat: 14 },
    { number: 62, name: "Al-Jumu'ah", totalAyat: 11 },
    { number: 63, name: "Al-Munafiqun", totalAyat: 11 },
    { number: 64, name: "At-Taghabun", totalAyat: 18 },
    { number: 65, name: "Ath-Thalaq", totalAyat: 12 },
    { number: 66, name: "At-Tahrim", totalAyat: 12 },
    { number: 67, name: "Al-Mulk", totalAyat: 30 },
    { number: 68, name: "Al-Qalam", totalAyat: 52 },
    { number: 69, name: "Al-Haqqah", totalAyat: 52 },
    { number: 70, name: "Al-Ma'arij", totalAyat: 44 },
    { number: 71, name: "Nuh", totalAyat: 28 },
    { number: 72, name: "Al-Jin", totalAyat: 28 },
    { number: 73, name: "Al-Muzzammil", totalAyat: 20 },
    { number: 74, name: "Al-Muddatstsir", totalAyat: 56 },
    { number: 75, name: "Al-Qiyamah", totalAyat: 40 },
    { number: 76, name: "Al-Insan", totalAyat: 31 },
    { number: 77, name: "Al-Mursalat", totalAyat: 50 },
    { number: 78, name: "An-Naba'", totalAyat: 40 },
    { number: 79, name: "An-Nazi'at", totalAyat: 46 },
    { number: 80, name: "'Abasa", totalAyat: 42 },
    { number: 81, name: "At-Takwir", totalAyat: 29 },
    { number: 82, name: "Al-Infithar", totalAyat: 19 },
    { number: 83, name: "Al-Muthaffifin", totalAyat: 36 },
    { number: 84, name: "Al-Insyiqaq", totalAyat: 25 },
    { number: 85, name: "Al-Buruj", totalAyat: 22 },
    { number: 86, name: "Ath-Thariq", totalAyat: 17 },
    { number: 87, name: "Al-A'la", totalAyat: 19 },
    { number: 88, name: "Al-Ghasyiyah", totalAyat: 26 },
    { number: 89, name: "Al-Fajr", totalAyat: 30 },
    { number: 90, name: "Al-Balad", totalAyat: 20 },
    { number: 91, name: "Asy-Syams", totalAyat: 15 },
    { number: 92, name: "Al-Lail", totalAyat: 21 },
    { number: 93, name: "Adh-Dhuha", totalAyat: 11 },
    { number: 94, name: "Asy-Syarh", totalAyat: 8 },
    { number: 95, name: "At-Tin", totalAyat: 8 },
    { number: 96, name: "Al-'Alaq", totalAyat: 19 },
    { number: 97, name: "Al-Qadr", totalAyat: 5 },
    { number: 98, name: "Al-Bayyinah", totalAyat: 8 },
    { number: 99, name: "Az-Zalzalah", totalAyat: 8 },
    { number: 100, name: "Al-'Adiyat", totalAyat: 11 },
    { number: 101, name: "Al-Qari'ah", totalAyat: 11 },
    { number: 102, name: "At-Takatsur", totalAyat: 8 },
    { number: 103, name: "Al-'Ashr", totalAyat: 3 },
    { number: 104, name: "Al-Humazah", totalAyat: 9 },
    { number: 105, name: "Al-Fil", totalAyat: 5 },
    { number: 106, name: "Quraisy", totalAyat: 4 },
    { number: 107, name: "Al-Ma'un", totalAyat: 7 },
    { number: 108, name: "Al-Kautsar", totalAyat: 3 },
    { number: 109, name: "Al-Kafirun", totalAyat: 6 },
    { number: 110, name: "An-Nashr", totalAyat: 3 },
    { number: 111, name: "Al-Masad", totalAyat: 5 },
    { number: 112, name: "Al-Ikhlas", totalAyat: 4 },
    { number: 113, name: "Al-Falaq", totalAyat: 5 },
    { number: 114, name: "An-Nas", totalAyat: 6 },
];

export const SURAH_MAP: Map<number, SurahInfo> = new Map(SURAH_LIST.map((s) => [s.number, s]));